filetype: arbasm

detect:
    filename: "\\.(aasm|aa)$"

rules:
    # This file is made for Arbitrary Assembly, it is adapted from the NASM assembly file from micro itself

    ## Instructions
    - statement: "\\b(?i)(set|dset|dget|rev|sel|inc|dec|add|sub|mul|div|mod|cmp|ucmp|rot|shf|app|print|nprint|sprint|fread|fwrite|input|sinput|draw|len|dset|dget)(?-i)\\b"
    - statement: "\\b(?i)(push|pop|peek|flip|ret)(?-i)\\b"

      ## Registers
    - identifier: "\\b(?i)(gr1|gr2|gr3|gr4|ir|flag|inplen|endian|stacsz|mstptr|rstptr|ptime|time|loop)(?-i)\\b"
    - identifier: "\\b(?i)(qr1|qr2|qr3|qr4)(?-i)\\b"

      ## Constants
      # Number - it works
    - constant.number: "\\b[0-9 \ ]+(|\ )+(|i|j|k)+\\b"

      ## Other
    - statement: "\\b(?i)(SCR|SAVE|LOAD)(?-i)\\b"
    - statement: "\\b(?i)(Ce|Cg|Cs)(?-i)\\b"
    - identifier: "[a-z A-Z 0-9 _]+:"

    - constant.string:
        start: "\""
        end: "\""
        skip: "\\\\."
        rules:
            - constant.specialChar: "\\\\."

    - comment:
        start: ";"
        end: "$"
        rules:
            - todo: "(TODO|XXX|FIXME):?"
