filetype: arbasm

detect:
    filename: "\\.(aa|aasm|arbasm)$"

rules:
    # This file is made for Arbitrary Assembly, it is adapted from the NASM assembly file from micro itself

    ## Instructions
    ## aasm
    - statement: "\\b(?i)(help)(?-i)\\b"
    - statement: "([>])"
    ## stdlib
    - statement: "\\b(?i)(set|dget|dset|len|rot|shf|rev)(?-i)\\b"
    - statement: "\\b(?i)(trun|app|sel|cut|ins)(?-i)\\b"
    - statement: "\\b(?i)(inc|dec|add|sub|rsub|mul|div|mod|root)(?-i)\\b"
    - statement: "\\b(?i)(print|nprint|sprint|input|sinput|fread|fwrite|flen)(?-i)\\b"
    - statement: "\\b(?i)(cmp|ucmp|Ce|Cn|Cg|Cs)(?-i)\\b"
    - statement: "\\b(?i)(jmp|rjmp|rmr)(?-i)\\b"
    - statement: "\\b(?i)(push|pop|peek|flip|ret)(?-i)\\b"
    - statement: "\\b(?i)(cton|ntoc|ston|ntos)(?-i)\\b"
    - statement: "\\b(?i)(run|prun|rand)(?-i)\\b"
    - statement: "\\b(?i)(SAVE|LOAD)(?-i)\\b"
    - symbol.operator: "[,+]"
    ## Quaternion operations
    - statement: "\\b(?i)(qset|qprint|qdset|qdget|qadd|qsub|scmul|scdiv|scmod|qmul|qdiv|qmod|conj|pysq|vshf)(?-i)\\b"
    - statement: "\\b(?i)(qpush|qpop|qflip|qret)(?-i)\\b"

      ## Registers
    - identifier: "\\b(?i)(gr1|gr2|gr3|gr4|gr5|gr6|ir|jr|ans)(?-i)\\b"
    - identifier: "\\b(?i)(inplen|endian|decip|path)(?-i)\\b"
    - identifier: "\\b(?i)(stacsz|mstptr|rstptr|offset)(?-i)\\b"
    - identifier: "\\b(?i)(time|ptime)(?-i)\\b"
    - identifier: "\\b(?i)(flag|loop)(?-i)\\b"
    - identifier: "\\b(?i)(qr1|qr2|qr3|qr4|qns)(?-i)\\b"

      ## Constants
      # Number - it works
    - constant.number: "\\b[0-9 ijk]+\\b"
    - constant.number: "[-]"
    - constant.number: ":+[a-z A-Z 0-9]+\\b"
    - identifier: "[$]"

      ## Other

    - constant.string:
        start: "\""
        end: "\""
        skip: "\\\\."
        rules:
            - constant.specialChar: "\\\\."

    - comment:
        start: "(;|#)"
        end: "$"
        rules:
            - todo: "(TODO|XXX|FIXME|rst|mst|--|[)]|[(]):?"
