name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Make the program
      run: make
    
    - name: Install mingw-gcc
      run: sudo apt install gcc-mingw-w64-x86-64 -y
    
    - name: Build Windows executable
      run: make windows
      
    - name: Test
      run: ./aasm SCR_scripts/test.aa -e
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          ./aasm
          ./aasm.exe
          ./scripts/
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
